Feature/ccv2 common branch
mojaloop/iac-ansible-collection-roles pull request #80
Opened 2024-09-19 17:19 UTC by sijo5722-2021

2024-09-20 12:03 UTC, dfry requested changes
please address adding sort

2024-09-20 12:03 UTC, dfry commented on mojaloop/iac/playbooks/argoeks_cluster_deploy.yaml
> +- hosts: "{{ groups['bastion'] | first }}"
add sort filter here as well please @jmutai

2024-09-23 07:44 UTC, jmutai commented on mojaloop/iac/playbooks/argoeks_cluster_deploy.yaml
> +- hosts: "{{ groups['bastion'] | first }}"
update done.

2024-09-24 11:17 UTC, dfry approved these changes
lgtm

2024-09-24 11:17 UTC, merged